//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccination
    {
        public int id_vaccination { get; set; }
        public string id_client { get; set; }
        public Nullable<System.DateTime> date_vaccination { get; set; }
        public Nullable<int> id_product { get; set; }
    
        public virtual client client { get; set; }
        public virtual product product { get; set; }
    }
}
